name: app_sintec
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_sign_in: ^4.5.1
  http: ^0.12.2
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.5
  tabbar: ^0.0.3
  intro_slider: ^2.3.1
  flutter_svg: ^0.17.0
  splashscreen: ^1.2.0
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/mobile_life.svg
    - assets/icons/company.jpg
    - assets/icons/drone.png
    - assets/icons/photo.png
    - assets/icons/google.png
    - assets/icons/maps.jpg
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
